BOT_TOKEN = 'BOT TOKEN'

USER_TOKEN = 'USER ACCOUNT TOKEN'

TWITTER_CON_KEY = 'TWITTER CONSUMER KEY'

TWITTER_CON_SECRET = 'TWITTER CONSUMER SECRET'

TWITTER_TOKEN_KEY = 'TWITTER TOKEN KEY'

TWITTER_TOKEN_SECRET = 'TWITTER TOKEN SECRET'

SLEEPER_TOKEN = "SLEEPER JWT TOKEN"