BOT_TOKEN = 'BOT TOKEN'

USER_TOKEN = 'USER ACCOUNT TOKEN'

TWITCH_CREDS = 'TWITCH TOKEN'

TWITTER_CON_KEY = 'TWITTER CONSUMER KEY'

TWITTER_CON_SECRET = 'TWITTER CONSUMER SECRET KEY'

TWITTER_TOKEN_KEY = 'TWITTER TOKEN KEY'

TWITTER_TOKEN_SECRET = 'TWITTER TOKEN SECRET KEY'